# Generated by Django 3.2.6 on 2021-08-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='plevel',
            field=models.CharField(choices=[(1, 'P1'), (2, 'P2'), (3, 'P3')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
