# Generated by Django 3.2.6 on 2021-08-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210829_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='plevel',
            new_name='priority',
        ),
    ]
