# Generated by Django 3.2.6 on 2021-08-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'P1'), ('1', 'P2'), ('2', 'P3')], default='', max_length=5),
        ),
    ]
